"""add index to api_token.token

Revision ID: 1eabe34fc47f
Revises: a57b39ddc27d
Create Date: 2026-04-30 11:57:07.504569

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "1eabe34fc47f"
down_revision: Union[str, Sequence[str], None] = "a57b39ddc27d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_api_token_token"), "api_token", ["token"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_api_token_token"), table_name="api_token")
    # ### end Alembic commands ###
