"""add scopes to api_token

Revision ID: a57b39ddc27d
Revises: 0558f826b297
Create Date: 2026-04-30 10:01:46.226096

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a57b39ddc27d"
down_revision: Union[str, Sequence[str], None] = "0558f826b297"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_token", sa.Column("scopes", sa.ARRAY(sa.String()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_token", "scopes")
    # ### end Alembic commands ###
